services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - "8080:80" #8080 local 80 in docker image
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data



volumes:
  postgres-data: