services:

  postgres:
    image: postgres:14.2
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data/
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    image: mongo:4.2.16-bionic
    ports:
      - "27017:27017"
    environment:
      MONGO_INIT_DB_DATABASE: logs
      MONGO_INIT_DB_ROOT_USERNAME: admin
      MONGO_INIT_DB_ROOT_PASSWORD: password
    volumes:
      - log-mongo-data:/data/db

  broker-service:
    build:
      context: ./broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - "8080:80" #8080 local 80 in docker image
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: authentication-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres

volumes:
  auth-postgres-data:
  log-mongo-data: